### ISSUE TITLE
init_sts_session doesn't work for a default profile

### ISSUE THREAD

**Issue by seanieb** [nccgroup/AWS-recipes#13] opened 2017-06-23 21:58 UTC
When I use a named profile it works, when I use the default profile it doesn't prompt me for my MFA even if I explicitly name the profile as default. 
`./awsrecipes_init_sts_session.py --profile default`

**Comment by l01cd3v** [comment] 2017-06-24 00:53
Strange, I cannot reproduce this so far. Could you try to get the latest version of opinel (just pushed 3.0.14) and see if this fixes it?

If not, could you:
1. Make sure a MFA serial is configured  (though this should not matter for this issue)
2. Share the version of python and which OS you're using

Thanks

**Comment by l01cd3v** [comment] 2017-08-04 19:00
Closing for now as I cannot repro

**Closed by l01cd3v** 2017-08-04 19:00 UTC

**Comment by seanieb** [comment] 2017-08-04 19:02
Sorry, haven't gotten time to get back to it. Will try to repro again next week.

**Comment by l01cd3v** [comment] 2017-08-04 19:03
Sounds good, please reopen if it still happens and let me know which versions of OS/Python you're using, as well as the version of opinel and the commit ID for this repo.
